In [1]:
# CREATING NUMPY ARRAY
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [2]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

[1 3 2]


In [4]:
# ACCESSING ARRAY INDEX
import numpy as np
 
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Printing a range of Array
# with the use of slicing method
arr2 = arr[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]



Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [6]:
# BASIC ARRAY OPERATIONS
import numpy as np
 
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)

Adding 1 to every element: [[2 3]
 [4 5]]


In [7]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)


Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]



Sum of all array elements:  10


In [9]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)


Array sum:
 [[5 5]
 [5 5]]


In [12]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)


Array sum:
 [[5 5]
 [5 5]]


In [13]:
# MATH OPERATIONS ON DATA TYPE ARRAY
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print(Sum)

[[ 7. 13.]
 [ 4. 14.]]


In [14]:
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 

# Addition of all Array elements
Sum1 = np.sum(arr1)
print(Sum1)
 

19.0


In [15]:
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 

# Square root of Array
Sqrt = np.sqrt(arr1)
print(Sqrt)
 
 

[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [16]:
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 

# Transpose of Array
Trans_arr = arr1.T
print(Trans_arr)

[[4. 2.]
 [7. 6.]]


In [17]:
# BASIC SLICING AND INDEXING
import numpy as np  
a = np.arange(20)

print("a[15] =", a[15])
print("a[-8:17:1] =", a[-8:17:1])
print("a[10:] =", a[10:])

a[15] = 15
a[-8:17:1] = [12 13 14 15 16]
a[10:] = [10 11 12 13 14 15 16 17 18 19]


In [18]:
# ADVANCED INDEXING
import numpy as np
a = np.array( [[1, 2], [3, 4], [5, 6]] )
print( a[[0, 1, 2], [0, 0, 1]] )

[1 3 6]


In [19]:
# MATRIX OPERATIONS IN NUMPY
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Addition:\n", np.add(x, y))
print("Subtraction:\n", np.subtract(x, y))
print("Division:\n", np.divide(x, y))

Addition:
 [[ 8 10]
 [13 15]]
Subtraction:
 [[-6 -6]
 [-5 -5]]
Division:
 [[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [20]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Element-wise multiplication:\n", np.multiply(x, y))
print("Matrix multiplication:\n", np.dot(x, y))

Element-wise multiplication:
 [[ 7 16]
 [36 50]]
Matrix multiplication:
 [[25 28]
 [73 82]]


In [21]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Square root:\n", np.sqrt(x))
print("Sum of all elements:", np.sum(y))

print("Column-wise sum:", np.sum(y, axis=0))
print("Row-wise sum:", np.sum(y, axis=1))
print("Transpose:\n", x.T)

Square root:
 [[1.         1.41421356]
 [2.         2.23606798]]
Sum of all elements: 34
Column-wise sum: [16 18]
Row-wise sum: [15 19]
Transpose:
 [[1 4]
 [2 5]]
